ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "caseName" TEXT NOT NULL DEFAULT 'Clinical case';
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'cosmetic-dentistry';
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "treatmentDuration" TEXT;
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "caseDate" TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "verifiedCase" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "consentConfirmed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BeforeAfter" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BeforeAfter" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
