ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "slug" TEXT;
UPDATE "Branch" SET "slug" = LOWER(REGEXP_REPLACE(REGEXP_REPLACE(COALESCE("name", 'branch'), '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g'))
  WHERE "slug" IS NULL OR "slug" = '';
ALTER TABLE "Branch" ALTER COLUMN "slug" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "Branch_slug_key" ON "Branch"("slug");

ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "address" TEXT;
UPDATE "Branch" SET "address" = COALESCE("location", "name") WHERE "address" IS NULL;
ALTER TABLE "Branch" ALTER COLUMN "address" SET NOT NULL;

ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT 'Mumbai';
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "pinCode" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "whatsapp" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "mapUrl" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "mapEmbedUrl" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "latitude" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "longitude" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "weeklySchedule" JSONB;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "doctorIds" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "serviceIds" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "published" BOOLEAN NOT NULL DEFAULT true;

UPDATE "Branch" SET "phone" = COALESCE("phone", '') WHERE "phone" IS NULL;
ALTER TABLE "Branch" ALTER COLUMN "phone" SET NOT NULL;

ALTER TABLE "Appointment" ADD COLUMN IF NOT EXISTS "branchId" TEXT REFERENCES "Branch"("id") ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "Appointment_branchId_idx" ON "Appointment"("branchId");
