CREATE TABLE IF NOT EXISTS "ServiceCategory" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL UNIQUE,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "whatIsTreatment" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "icon" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "categoryId" TEXT REFERENCES "ServiceCategory"("id") ON DELETE SET NULL;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "treatmentDuration" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "hidePrice" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "benefits" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "treatmentSteps" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "faqs" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
