ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "thumbnailUrl" TEXT;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "durationSeconds" INTEGER;
ALTER TABLE "Media" ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0;
